"""Emit the constant tables march.asm needs.

  gen_slopes.inc   72 headings x 8 signed 16-bit Q6.10 per-heading constants
                   (the view-space basis + the two frustum-plane step pairs)
  gen_maze.inc     the 16x16 SOLID array from tools/world.py

The march is self-contained on purpose: it reads NOTHING from the &4000
table bank, so engine2/src/test_march.asm can exercise it on its own.  The
basis words are gentab.t_basis() verbatim, so the endpoints the march files
are in exactly the projector's Q6.10 view space.

Run: PYTHONPATH=tools:engine2/tools python3 engine2/tools/gen_march.py engine2/src
"""

import os
import sys

import world
import marchmodel as M


def emit_slopes(f):
    f.write("; generated by engine2/tools/gen_march.py -- do not edit\n")
    f.write("VBITS  equ %d\n" % M.VBITS)
    f.write("ZNEARM equ %d\n" % M.ZNEAR_M)
    f.write("MSLACK equ %d\n" % M.SLACK)
    f.write("RMAX   equ %d\n\n" % M.R_MAX)
    f.write("; per heading, 16 bytes, all Q6.10:\n")
    f.write(";   rgtx rgty fwdx fwdy   step of (xv, zv) for i -> i+1 / j -> j+1\n")
    f.write(";   dLi  dLj  dRi  dRj    step of the left / right plane value\n")
    f.write("MARCHTAB\n")
    for a in range(M.N_ANGLES):
        rgtx, rgty, fwdx, fwdy = M.BASIS[a]
        dli, dlj, dri, drj = M.LRSTEP[a]
        f.write("    dw %6d,%6d,%6d,%6d,%6d,%6d,%6d,%6d   ; %d\n"
                % (rgtx, rgty, fwdx, fwdy, dli, dlj, dri, drj, a))


def emit_maze(f, solid, sx, sy):
    f.write("; generated by engine2/tools/gen_march.py -- do not edit\n")
    f.write("START_X equ %d\nSTART_Y equ %d\n" % (sx, sy))
    # HOW MANY DOORS THE MAP HAS, so game.asm's MAXDOORS cannot be too
    # small for it.  game_init registers at most MAXDOORS doors and
    # SILENTLY skips the rest, and a skipped door can never be opened --
    # this map grew to twelve doors against a MAXDOORS of eight, and the
    # four it dropped included the one beside the player's start cell.
    # main3.asm asserts MAXDOORS >= NDOORS, so the map now sizes the
    # engine instead of the engine quietly truncating the map.
    f.write("NDOORS  equ %d\n\n"
            % sum(1 for v in solid if v == world.DOOR))
    f.write("MAZEDATA\n")
    for y in range(16):
        f.write("    db " + ",".join(str(solid[y * 16 + x])
                                     for x in range(16)) + "\n")


def main(outdir):
    grid, sx, sy = world.load_maze()
    solid = M.solid_from_grid(grid)
    with open(os.path.join(outdir, "gen_slopes.inc"), "w") as f:
        emit_slopes(f)
    with open(os.path.join(outdir, "gen_maze.inc"), "w") as f:
        emit_maze(f, solid, sx, sy)
    print("wrote gen_slopes.inc, gen_maze.inc to", outdir)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "engine2/src")
