#!/usr/bin/env python3
"""Generate the arithmetic tables for engine2's math kernel.

Emitted into engine2/src/mathdata.inc, laid out so that every lookup is a
2- or 3-instruction indexed read:

  QSLO/QSHI   &4000/&4200  quarter squares  QS[i] = (i*i)>>2, i = 0..511
                           a*b = QS[a+b] - QS[|a-b|]   (exact for u8 x u8)
                           QSHI = QSLO+512 so `inc h : inc h` reaches the
                           high byte from EITHER page of the low table.
  RECLO/RECHI &4400/&4500  RT[i] = round(2^20/(256+i)), i = 0..255
                           (nine-bit mantissa; bit 8 is implicit)
  TRIG        &4600   +0   COSMAG[72]  round(|cos|*128)  0..128
                      +72  SINMAG[72]  round(|sin|*128)  0..128
                      +144 SGNS[72]    bit0 = cos<0, bit1 = sin<0
  COSQ88      &4700   72 signed words, round(cos*256)   } the lattice
  SINQ88      &4800   72 signed words, round(sin*256)   } rotator
  JTAB        &4900   68 bytes of RAM scratch (built per frame)
  QSQW        &4A00   the quarter squares AGAIN, interleaved as words --
                      built only so the two table layouts can be timed
                      head to head; the shipped engine needs only one.

ROM/bank cost of the real tables: 1024 + 512 + 216 + 144 + 144 = 2040 bytes,
plus 68 bytes of RAM scratch.
"""

import math
import os
import sys

N_ANGLES = 72
DEG_STEP = 360.0 / N_ANGLES

QSLO = 0x4000
QSHI = 0x4200
RECLO = 0x4400
RECHI = 0x4500
TRIG = 0x4600           # cos/sin magnitudes + signs (216 bytes)
COSQ88 = 0x4700         # round(cos*256) signed 16-bit, 144 bytes
SINQ88 = 0x4800         # round(sin*256) signed 16-bit, 144 bytes
JTAB = 0x4900           # RAM scratch for the lattice rotator (68 bytes)
QSQW = 0x4A00           # SAME quarter squares, INTERLEAVED as words --
                        # only assembled so the two layouts can be timed

RECIP_SCALE = 1 << 20   # RT[m] = RECIP_SCALE / m


def quarter_squares():
    return [(i * i) >> 2 for i in range(512)]


def recip_table():
    """RT[i] = round(2^20 / (256+i)) -- a NINE bit mantissa, indexed by its
    low byte because bit 8 is always set."""
    return [int(round(RECIP_SCALE / (256 + i))) for i in range(256)]


def trig_tables():
    cm, sm, sg, cq, sq = [], [], [], [], []
    for a in range(N_ANGLES):
        r = math.radians(a * DEG_STEP)
        c = int(round(math.cos(r) * 128.0))
        s = int(round(math.sin(r) * 128.0))
        cm.append(abs(c))
        sm.append(abs(s))
        sg.append((1 if c < 0 else 0) | (2 if s < 0 else 0))
        cq.append(int(round(math.cos(r) * 256.0)) & 0xFFFF)
        sq.append(int(round(math.sin(r) * 256.0)) & 0xFFFF)
    return cm, sm, sg, cq, sq


def db(vals, per=16):
    out = []
    for i in range(0, len(vals), per):
        out.append("    db " + ",".join("#%02X" % v for v in vals[i:i + per]))
    return "\n".join(out)


def dw(vals, per=8):
    out = []
    for i in range(0, len(vals), per):
        out.append("    dw " + ",".join("#%04X" % v for v in vals[i:i + per]))
    return "\n".join(out)


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "src", "mathdata.inc")

    qs = quarter_squares()
    rt = recip_table()
    cm, sm, sg, cq, sq = trig_tables()

    L = []
    L.append("; GENERATED by engine2/tools/gen_math_tables.py -- do not edit")
    L.append("")
    L.append("QSLO   equ #%04X" % QSLO)
    L.append("QSHI   equ #%04X" % QSHI)
    L.append("RECLO  equ #%04X" % RECLO)
    L.append("RECHI  equ #%04X" % RECHI)
    L.append("TRIG   equ #%04X" % TRIG)
    L.append("COSQ88 equ #%04X" % COSQ88)
    L.append("SINQ88 equ #%04X" % SINQ88)
    L.append("JTAB   equ #%04X" % JTAB)
    L.append("QSQW   equ #%04X" % QSQW)
    L.append("RECIP_SCALE equ %d" % RECIP_SCALE)
    L.append("")
    L.append("    org QSLO")
    L.append(db([v & 0xFF for v in qs]))
    L.append("    org QSHI")
    L.append(db([v >> 8 for v in qs]))
    L.append("    org RECLO")
    L.append(db([v & 0xFF for v in rt]))
    L.append("    org RECHI")
    L.append(db([v >> 8 for v in rt]))
    L.append("    org TRIG")
    L.append(db(cm))
    L.append(db(sm))
    L.append(db(sg))
    L.append("    org COSQ88")
    L.append(dw(cq))
    L.append("    org SINQ88")
    L.append(dw(sq))
    L.append("    org JTAB")
    L.append("    defs 68,0")
    L.append("    org QSQW")
    L.append(dw(qs))
    L.append("")

    with open(out, "w") as fh:
        fh.write("\n".join(L) + "\n")
    print("wrote %s  (qs=%d recip=%d trig=%d)" % (out, len(qs), len(rt), len(cm)))


if __name__ == "__main__":
    main()
