"""Emit the constant tables march.asm needs.

  gen_slopes.inc   72 headings x 8 signed 16-bit Q6.10 per-heading constants
                   (the view-space basis + the two frustum-plane step pairs)
  gen_maze.inc     the 16x16 SOLID array from tools/world.py

The march is self-contained on purpose: it reads NOTHING from the &4000
table bank, so engine2/src/test_march.asm can exercise it on its own.  The
basis words are gentab.t_basis() verbatim, so the endpoints the march files
are in exactly the projector's Q6.10 view space.

Run: PYTHONPATH=tools:engine2/tools python3 engine2/tools/gen_march.py engine2/src
"""

import os
import sys

import world
import marchmodel as M


def emit_slopes(f):
    """The march's scalar constants.  THE TABLE ITSELF IS NOT HERE ANY
    MORE -- see emit_mtab below and gentex.py: 1152 bytes for one 16-byte
    copy a frame was the largest single thing left in a code segment
    whose ceiling assert has fired twelve times."""
    f.write("; generated by engine2/tools/gen_march.py -- do not edit\n")
    f.write("VBITS  equ %d\n" % M.VBITS)
    f.write("ZNEARM equ %d\n" % M.ZNEAR_M)
    f.write("MSLACK equ %d\n" % M.SLACK)
    f.write("RMAX   equ %d\n" % M.R_MAX)


def emit_mtab(f):
    """MARCHTB in BASE RAM, for engine2/src/test_march.asm ONLY.

    The shipped disc reads these out of RAM bank 5, where gentex.py puts
    them, and march.asm pages the bank in around the one LDIR that wants
    them.  test_march.asm cannot: it runs AT &4000, which is the window
    the bank is paged over, so the OUT would delete the code executing
    it.  It gets this file instead -- the same 1152 bytes, at a label
    rather than an equ -- and leaves MTBANK undefined so march.asm skips
    the paging.  ONE generator writes both, so they cannot drift.
    """
    f.write("; generated by engine2/tools/gen_march.py -- do not edit\n")
    f.write("; per heading, 16 bytes, all Q6.10:\n")
    f.write(";   rgtx rgty fwdx fwdy   step of (xv, zv) for i -> i+1 / j -> j+1\n")
    f.write(";   dLi  dLj  dRi  dRj    step of the left / right plane value\n")
    f.write("MARCHTB\n")
    for a in range(M.N_ANGLES):
        rgtx, rgty, fwdx, fwdy = M.BASIS[a]
        dli, dlj, dri, drj = M.LRSTEP[a]
        f.write("    dw %6d,%6d,%6d,%6d,%6d,%6d,%6d,%6d   ; %d\n"
                % (rgtx, rgty, fwdx, fwdy, dli, dlj, dri, drj, a))


def emit_maze(f, solid, sx, sy):
    f.write("; generated by engine2/tools/gen_march.py -- do not edit\n")
    f.write("START_X equ %d\nSTART_Y equ %d\n" % (sx, sy))
    # HOW MANY DOORS THE MAP HAS, so game.asm's MAXDOORS cannot be too
    # small for it.  game_init registers at most MAXDOORS doors and
    # SILENTLY skips the rest, and a skipped door can never be opened --
    # this map grew to twelve doors against a MAXDOORS of eight, and the
    # four it dropped included the one beside the player's start cell.
    # main3.asm asserts MAXDOORS >= NDOORS, so the map now sizes the
    # engine instead of the engine quietly truncating the map.
    f.write("NDOORS  equ %d\n\n"
            % sum(1 for v in solid if v == world.DOOR))
    # ---- PACKED, TWO BITS A CELL ------------------------------------
    #  SOLID's alphabet is 0 open, 1 wall, 2 shut door, 3 door in motion,
    #  so a cell is two bits and the whole map is 64 bytes rather than
    #  256.  march.asm:maze_unpack spreads it back out at startup.
    #
    #  THIS IS NOT MICRO-OPTIMISATION, IT IS THE BODY BUDGET.  main3.asm
    #  asserts `game_end <= BUCK0` and that assert has now fired nine
    #  times; the ammo scanner put it 50 bytes over again.  192 bytes of
    #  a 256-byte table that is read ONCE, at startup, and then never
    #  again was the cheapest 192 bytes in the file to give back.
    #
    #  Cell i lives in bits (i & 3) * 2 of byte i >> 2 -- lowest cell in
    #  the lowest bits, so the unpacker shifts right and never has to
    #  count backwards.
    assert all(0 <= v <= 3 for v in solid), "SOLID no longer fits two bits"
    f.write("MAZEDATA        ; 16x16 cells, two bits each, low cell low bits\n")
    for i in range(0, 256, 32):
        row = []
        for j in range(i, i + 32, 4):
            row.append(solid[j] | (solid[j + 1] << 2)
                       | (solid[j + 2] << 4) | (solid[j + 3] << 6))
        f.write("    db " + ",".join("#%02X" % b for b in row)
                + "   ; cells %d-%d\n" % (i, i + 31))


def emit_monster(f, cell):
    """Where the one monster STARTS, as a MAZEDATA cell index.

    TWO SYMBOLS FOR ONE NUMBER, AND THAT IS THE POINT.  MONCELL is a
    BYTE and it MOVES: game.asm's mon_move writes a new cell into it
    every MON_RATE frames, and mon_hit writes #FF when the thing dies.
    MONSTART is an equ -- the map's own value, which nothing can
    overwrite -- so game_init can put the monster back where the map
    put it.  Without it a restart would resurrect the monster wherever
    it happened to be standing when it was shot, which for a dead one
    is nowhere at all.

    #FF in either puts no monster on the map.
    """
    n = "#FF" if cell is None else "%d" % (cell[1] * 16 + cell[0])
    where = "" if cell is None else "   ; %d,%d" % cell
    f.write("\nMONSTART    equ %s%s   ; where the map puts the monster\n"
            % (n, where))
    f.write("MONCELL     db  MONSTART   ; ...and where it is NOW, y*16+x\n")


def emit_ammo(f, cells):
    """The pickup list, as MAZEDATA cell indices.

    One byte a pickup, y*16+x -- the same index the march and the collision
    already use, so game.asm compares the player's cell against these
    directly and never has to unpack a coordinate pair.
    """
    f.write("\nNAMMO   equ %d\n" % len(cells))
    f.write("AMMOTAB\n")
    if cells:
        f.write("    db " + ",".join("%d" % (y * 16 + x) for x, y in cells)
                + "   ; " + " ".join("%d,%d" % c for c in cells) + "\n")


def main(outdir):
    grid, sx, sy = world.load_maze()
    solid = M.solid_from_grid(grid)
    with open(os.path.join(outdir, "gen_slopes.inc"), "w") as f:
        emit_slopes(f)
    with open(os.path.join(outdir, "gen_mtab.inc"), "w") as f:
        emit_mtab(f)
    with open(os.path.join(outdir, "gen_maze.inc"), "w") as f:
        emit_maze(f, solid, sx, sy)
        emit_ammo(f, world.ammo_cells(grid, sx, sy))
        emit_monster(f, world.monster_cell(grid, sx, sy))
    print("wrote gen_slopes.inc, gen_mtab.inc, gen_maze.inc to", outdir)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "engine2/src")
