"""Emit the constant tables march.asm needs.

  gen_slopes.inc   72 headings x 8 signed 16-bit Q6.10 per-heading constants
                   (the view-space basis + the two frustum-plane step pairs)
  gen_maze.inc     the 16x16 SOLID array from tools/world.py

The march is self-contained on purpose: it reads NOTHING from the &4000
table bank, so engine2/src/test_march.asm can exercise it on its own.  The
basis words are gentab.t_basis() verbatim, so the endpoints the march files
are in exactly the projector's Q6.10 view space.

Run: PYTHONPATH=tools:engine2/tools python3 engine2/tools/gen_march.py engine2/src
"""

import math
import os
import sys

import world
import marchmodel as M


def emit_slopes(f):
    """The march's scalar constants.  THE TABLE ITSELF IS NOT HERE ANY
    MORE -- see emit_mtab below and gentex.py: 1152 bytes for one 16-byte
    copy a frame was the largest single thing left in a code segment
    whose ceiling assert has fired twelve times."""
    f.write("; generated by engine2/tools/gen_march.py -- do not edit\n")
    f.write("VBITS  equ %d\n" % M.VBITS)
    f.write("ZNEARM equ %d\n" % M.ZNEAR_M)
    f.write("MSLACK equ %d\n" % M.SLACK)
    f.write("RMAX   equ %d\n" % M.R_MAX)


def emit_mtab(f):
    """MARCHTB in BASE RAM, for engine2/src/test_march.asm ONLY.

    The shipped disc reads these out of RAM bank 5, where gentex.py puts
    them, and march.asm pages the bank in around the one LDIR that wants
    them.  test_march.asm cannot: it runs AT &4000, which is the window
    the bank is paged over, so the OUT would delete the code executing
    it.  It gets this file instead -- the same 1152 bytes, at a label
    rather than an equ -- and leaves MTBANK undefined so march.asm skips
    the paging.  ONE generator writes both, so they cannot drift.
    """
    f.write("; generated by engine2/tools/gen_march.py -- do not edit\n")
    f.write("; per heading, 16 bytes, all Q6.10:\n")
    f.write(";   rgtx rgty fwdx fwdy   step of (xv, zv) for i -> i+1 / j -> j+1\n")
    f.write(";   dLi  dLj  dRi  dRj    step of the left / right plane value\n")
    f.write("MARCHTB\n")
    for a in range(M.N_ANGLES):
        rgtx, rgty, fwdx, fwdy = M.BASIS[a]
        dli, dlj, dri, drj = M.LRSTEP[a]
        f.write("    dw %6d,%6d,%6d,%6d,%6d,%6d,%6d,%6d   ; %d\n"
                % (rgtx, rgty, fwdx, fwdy, dli, dlj, dri, drj, a))


def start_heading(sx, sy, mon):
    """-> the heading, 0..N_ANGLES-1, that the player starts facing.

    IT POINTS AT THE MONSTER, AND THAT IS NOT DECORATION.  game_init used
    to set plr_a = 0 -- due east -- and the map puts the monster two
    cells WEST of the start, which is directly behind the player's head.

    Once the monster walked, that made the first ten seconds of the game
    unsurvivable and unreadable.  MEASURED on the booted disc: the
    monster steps adjacent on frame 6 and bites every MON_RATE frames
    from frame 12, so five hit points are gone by frame 36.  Turning 180
    degrees is 36 frames at one 5-degree step a frame -- so a player who
    does not know to hold SHIFT is facing the wrong way for the whole of
    his first life, and dies without ever seeing what killed him.

    Deriving it from the two cells rather than writing a number down
    means a map that moves either of them keeps the opening legible.
    Headings run +x = 0 and CLOCKWISE on a map drawn with +y downward,
    which is the way turn_right takes plr_a and the way STEPTAB is
    built -- see game.asm.
    """
    if mon is None:
        return 0
    dx, dy = mon[0] - sx, mon[1] - sy
    a = int(round(math.degrees(math.atan2(dy, dx)) * M.N_ANGLES / 360.0))
    return a % M.N_ANGLES


def emit_maze(f, solid, sx, sy, mon):
    f.write("; generated by engine2/tools/gen_march.py -- do not edit\n")
    f.write("START_X equ %d\nSTART_Y equ %d\n" % (sx, sy))
    a = start_heading(sx, sy, mon)
    f.write("START_A equ %d   ; %d degrees -- facing the monster\n"
            % (a, a * 360 // M.N_ANGLES))
    # HOW MANY DOORS THE MAP HAS, so game.asm's MAXDOORS cannot be too
    # small for it.  game_init registers at most MAXDOORS doors and
    # SILENTLY skips the rest, and a skipped door can never be opened --
    # this map grew to twelve doors against a MAXDOORS of eight, and the
    # four it dropped included the one beside the player's start cell.
    # main3.asm asserts MAXDOORS >= NDOORS, so the map now sizes the
    # engine instead of the engine quietly truncating the map.
    f.write("NDOORS  equ %d\n\n"
            % sum(1 for v in solid if v == world.DOOR))
    # ---- PACKED, TWO BITS A CELL ------------------------------------
    #  SOLID's alphabet is 0 open, 1 wall, 2 shut door, 3 door in motion,
    #  so a cell is two bits and the whole map is 64 bytes rather than
    #  256.  march.asm:maze_unpack spreads it back out at startup.
    #
    #  THIS IS NOT MICRO-OPTIMISATION, IT IS THE BODY BUDGET.  main3.asm
    #  asserts `game_end <= BUCK0` and that assert has now fired nine
    #  times; the ammo scanner put it 50 bytes over again.  192 bytes of
    #  a 256-byte table that is read ONCE, at startup, and then never
    #  again was the cheapest 192 bytes in the file to give back.
    #
    #  Cell i lives in bits (i & 3) * 2 of byte i >> 2 -- lowest cell in
    #  the lowest bits, so the unpacker shifts right and never has to
    #  count backwards.
    assert all(0 <= v <= 3 for v in solid), "SOLID no longer fits two bits"
    # ---- THE BYTES ARE IN RAM BANK 6, NOT HERE.  engine2/tools/genaux.py
    #      reads them out of this file and gen_aux.inc names the address:
    #      64 bytes read once, by maze_unpack, when new_game rebuilds the
    #      world -- exactly what bank 6 is for.  They are still WRITTEN
    #      here, commented out, because this generator owns the map and a
    #      packing this file cannot show is a packing nobody can check.
    f.write("; MAZEDATA is in RAM bank 6 -- see gen_aux.inc and genaux.py.\n")
    f.write("; The bytes, for reading: 16x16 cells, two bits each, low cell\n")
    f.write("; in the low bits.\n")
    for i in range(0, 256, 32):
        row = []
        for j in range(i, i + 32, 4):
            row.append(solid[j] | (solid[j + 1] << 2)
                       | (solid[j + 2] << 4) | (solid[j + 3] << 6))
        f.write(";   " + ",".join("#%02X" % b for b in row)
                + "   ; cells %d-%d\n" % (i, i + 31))


def emit_monster(f, cells):
    """Where the monsters START, as MAZEDATA cell indices.

    TWO SYMBOLS FOR ONE NUMBER, AND THAT IS THE POINT.  MONCELL is a
    BYTE and it MOVES: game.asm's mon_move writes a new cell into it
    every MON_RATE frames, and mon_hit writes #FF when the thing dies.
    MONSTART is an equ -- the map's own value, which nothing can
    overwrite -- so game_init can put the monster back where the map
    put it.  Without it a restart would resurrect the monster wherever
    it happened to be standing when it was shot, which for a dead one
    is nowhere at all.

    #FF in either puts no monster on the map.
    """
    #  AND THERE ARE SEVERAL NOW.  MONSTARTS is the list the map wrote;
    #  game.asm's MONTAB is where they are NOW, in RAM, two bytes each --
    #  cell and hit points.  The pair MONSTART/MONCELL is kept for the
    #  single-monster state the drawing and the radar still use: the
    #  wrapper in game.asm swaps each monster through it in turn.
    f.write("\nNMON    equ %d   ; monsters the map puts out\n" % len(cells))
    if not cells:
        f.write("MONSTART    equ #FF   ; ...none on this layout\n")
        f.write("MONSTARTS   db #FF\n")
    else:
        f.write("MONSTART    equ %d   ; %d,%d -- the first of them\n"
                % (cells[0][1] * 16 + cells[0][0], cells[0][0], cells[0][1]))
        f.write("MONSTARTS               ; y*16+x, one a room\n")
        f.write("    db " + ",".join("%d" % (y * 16 + x) for x, y in cells)
                + "   ; " + " ".join("%d,%d" % c for c in cells) + "\n")
    f.write("MONCELL     db  MONSTART   ; the one being worked on now\n")


def emit_ammo(f, cells):
    """The pickup list, as MAZEDATA cell indices.

    One byte a pickup, y*16+x -- the same index the march and the collision
    already use, so game.asm compares the player's cell against these
    directly and never has to unpack a coordinate pair.
    """
    f.write("\nNAMMO   equ %d\n" % len(cells))
    f.write("AMMOTAB\n")
    if cells:
        f.write("    db " + ",".join("%d" % (y * 16 + x) for x, y in cells)
                + "   ; " + " ".join("%d,%d" % c for c in cells) + "\n")


def emit_exit(f, cell):
    """The way out, as a MAZEDATA cell index -- an EQU, not a byte.

    NOTHING WRITES IT, which is the whole difference from MONCELL: the
    exit does not move and cannot be consumed, so game.asm compares the
    player's cell against a constant and the test is `ld c,n` rather
    than a load.  #FF is "this layout has no exit", and it is safe by
    construction: #FF decodes to (15, 15), the corner of the outer wall,
    a cell no player can stand in -- so the test is simply never true.
    """
    n = "#FF" if cell is None else "%d" % (cell[1] * 16 + cell[0])
    where = "" if cell is None else "   ; %d,%d" % cell
    f.write("\nEXIT_CELL   equ %s%s   ; walk onto this and the level ends\n"
            % (n, where))
    f.write("EXIT_X      equ %d\nEXIT_Y      equ %d\n"
            % ((15, 15) if cell is None else cell))


def main(outdir):
    grid, sx, sy = world.load_maze()
    solid = M.solid_from_grid(grid)
    with open(os.path.join(outdir, "gen_slopes.inc"), "w") as f:
        emit_slopes(f)
    with open(os.path.join(outdir, "gen_mtab.inc"), "w") as f:
        emit_mtab(f)
    with open(os.path.join(outdir, "gen_maze.inc"), "w") as f:
        mons = world.monster_cells(grid, sx, sy)
        mon = mons[0] if mons else None
        emit_maze(f, solid, sx, sy, mon)
        emit_ammo(f, world.ammo_cells(grid, sx, sy))
        emit_monster(f, mons)
        emit_exit(f, world.exit_cell(grid, sx, sy))
    print("wrote gen_slopes.inc, gen_mtab.inc, gen_maze.inc to", outdir)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "engine2/src")
