"""engine2/tools/genpal.py -- THE GAME'S SIXTEEN PENS, AS A GIMP PALETTE.

    python3 engine2/tools/genpal.py     -> assets/amaze-mode0.gpl

WHY THIS EXISTS.  assets/sprites.png is painted by hand and read by
genspr.py, which will not guess: a pixel whose RGB is not one of these
sixteen is a hard error naming the pixel, because guessing is how a
sprite ends up a shade the CPC cannot show and nobody notices until it
is on a screen.  So the artist needs the exact sixteen in the editor,
and this is where they come from -- generated from tools/world.py's
PEN_INK through cpchw.INKS, so the palette in GIMP and the palette the
gate array is handed cannot be two different things.

INSTALLING IT.  GIMP 3 reads .gpl out of its own palette directory:

    cp assets/amaze-mode0.gpl ~/.config/GIMP/3.0/palettes/

then Windows > Dockable Dialogs > Palettes, and refresh.  Paint in
Indexed mode (Image > Mode > Indexed, "Use custom palette") and GIMP
will not let you make a colour that is not in it.

THE NAMES ARE THE ROLES, not the colours.  Pen 5 is "wall depth 5", not
"blue": what matters when you are drawing a monster is which pens are
already spoken for by the walls and the floor, because a sprite drawn in
them reads as scenery.  See the note at the foot of genspr.py.

TRANSPARENCY IS NOT A PEN.  There are sixteen and every one of them is
ink.  A sprite's transparent pixels are transparent in the PNG -- alpha
0 -- and genspr.py turns them into the ABSENCE of a rectangle, which is
what makes a silhouette cheaper than the block it replaces.
"""

import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(os.path.dirname(_HERE))
sys.path.insert(0, os.path.join(_ROOT, "tools"))

import cpchw as cpc                                             # noqa: E402
import world                                                    # noqa: E402

# What each pen is FOR.  world.py hands them out; this is that list read
# back as prose, and the order is the pen order so the palette index in
# GIMP IS the pen number.
ROLE = [
    "void beyond the frustum",
    "wall depth 1 (nearest)",
    "wall depth 2",
    "wall depth 3",
    "wall depth 4",
    "wall depth 5 (farthest)",
    "door depth 1",
    "door depth 2",
    "door depth 3 / ammo pips",
    "door depth 4",
    "floor near",
    "floor far",
    "ceiling near",
    "ceiling far / monster flesh",
    "HUD frame",
    "HUD text / highlight",
]

HEAD = """GIMP Palette
Name: AMazeCPC mode 0
Columns: 4
#
# GENERATED by engine2/tools/genpal.py -- do not edit.
#
# The sixteen pens of the Amstrad CPC mode 0 screen, in PEN order: the
# palette index here IS the pen number the Z80 writes.  Painted into
# assets/sprites.png and read back by engine2/tools/genspr.py, which
# rejects any colour that is not one of these.
#
# Transparency is alpha 0 in the PNG, not a colour.
#
"""


def gpl():
    lines = [HEAD]
    for pen, ink in enumerate(world.PEN_INK):
        r, g, b = cpc.ink_rgb(ink)
        lines.append(f"{r:3d} {g:3d} {b:3d}\t{pen:2d} {ROLE[pen]}")
    return "\n".join(lines) + "\n"


def main():
    out = os.path.join(_ROOT, "assets", "amaze-mode0.gpl")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w").write(gpl())
    print(f"{out}: 16 pens")
    for pen, ink in enumerate(world.PEN_INK):
        print(f"   pen {pen:2d}  ink {ink:2d}  "
              f"#{'%02X%02X%02X' % cpc.ink_rgb(ink)}  {ROLE[pen]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
