"""The COLUMN renderer's table bank -- RAM bank 5, and the include for it.

    python3 engine2/tools/gentex.py     # -> build/TEX.BIN + src/gen_tex.inc

WHY A SECOND BANK.  Bank 4 is the engine's table bank and it is FULL: a
build uses 16204 of its 16384 bytes, so there are 180 free and the two
textures alone are 8192.  Bank 5 is the next RAM configuration up
(`OUT (&7Fxx),&C5` puts physical bank 5 at &4000-&7FFF in place of bank 4)
and nothing in this program has ever used it.

WHAT IS IN IT, and every one of these exists to keep a DIVIDE out of the
per-column loop:

    &4000  TEXWALL   16 pages of 256 bytes -- the wall, TRANSPOSED
    &5000  TEXDOOR   16 pages of 256 bytes -- the door
    &6000  CTABT     1537 x 4 bytes        -- step and start index,
                                       indexed by h in QUARTER scanlines
    &7810  RTHRESH   (VP_BW+1) x 2 bytes   -- the u division's shift guard

THE TEXTURES ARE TRANSPOSED AND REPLICATED, which is the whole reason the
inner loop is ten microseconds a scanline and not twenty.  walltex.py
draws 32x64 Mode 0 PIXELS; two pixels are one byte, so that is 16 BYTE
columns of 64 rows, and each column is written as one contiguous run --
a column fill is then a linear source walk instead of a stride of 16.
Each 64-byte column is then replicated four times into a 256-byte PAGE,
so the vertical coordinate is a plain 8.8 number whose high byte is the
offset within the page: sampling it is `ld e,h : ld a,(de)` and nothing
else.  Masking a 64-byte column back into range would cost two more
microseconds a scanline -- 8 ms on a full frame -- against 4096 bytes of
a bank that was empty.

See engine2/tools/colmodel.py for the arithmetic all four tables serve;
it is the spec and this file only lays its output out in memory.
"""

import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_E2 = os.path.dirname(_HERE)
sys.path.insert(0, _HERE)

import colmodel
import walltex                                            # noqa: E402
import rastermodel as rm                                   # noqa: E402

BANK_BASE = 0x4000
BANK_SIZE = 0x4000
RAMCFG = 0xC5                       # OUT (&7Fxx), &C5 -> bank 5 at &4000

A_WALL = 0x4000
A_DOOR = 0x5000
A_CTAB = 0x6000
A_RTHR = 0x7810   # CTAB is 6148 bytes now, not 1540


def rthresh(c):
    """T[w] = the smallest x with w*x >= 16384.

    colmodel.normalise shifts the two half heights right until
    w*max(ha,hb) < 16384, which is what keeps the u division's remainder
    inside 16 bits when it shifts left.  On the Z80 that test has to be a
    COMPARE, not a multiply, so the threshold is tabulated per width.
    T[0] is never read (a zero-width face is dropped before this).
    """
    return [0 if w == 0 else -(-16384 // w) for w in range(c.VP_BW + 1)]


def build():
    c = rm.cfg()

    # ---- THE ART MUST HOLD THE INVARIANT ITS DETAIL SETTING PROMISES.
    #      walltex.DETAIL 0 exists so the fill can sample once per TWO
    #      scanlines without losing anything, and that is only true while
    #      no feature is one texel tall.  Retuning a stone height or a
    #      jitter can reintroduce one silently, so the BUILD checks it --
    #      the same way main3.asm asserts MAXDOORS >= NDOORS rather than
    #      trusting the map to stay small.
    if not walltex.DETAIL:
        for _name, _rows in (("wall", walltex.wall()),
                             ("door", walltex.door())):
            _n = walltex.single_rows(_rows)
            assert _n == 0, (
                "walltex.DETAIL is 0, which promises no feature is one "
                "texel tall, but the %s art has %d single-row runs -- the "
                "2x fill would drop them" % (_name, _n))

    blob = bytearray(A_RTHR - BANK_BASE)

    for base, pages in ((A_WALL, colmodel.wall_pages()),
                        (A_DOOR, colmodel.door_pages())):
        assert len(pages) == colmodel.TEX_BW
        for u, page in enumerate(pages):
            assert len(page) == colmodel.IDX_N
            o = base - BANK_BASE + u * colmodel.IDX_N
            blob[o:o + colmodel.IDX_N] = page

    tab = colmodel.CTAB()
    o = A_CTAB - BANK_BASE
    for step, idx0 in tab:
        blob[o] = step & 0xFF
        blob[o + 1] = step >> 8
        blob[o + 2] = idx0 & 0xFF
        blob[o + 3] = idx0 >> 8
        o += 4
    assert o <= A_RTHR - BANK_BASE, "CTAB has grown into RTHRESH"

    for w, t in enumerate(rthresh(c)):
        blob += bytes((t & 0xFF, t >> 8))

    assert len(blob) <= BANK_SIZE, (
        f"bank 5 overflows: {len(blob)} > {BANK_SIZE}")
    return bytes(blob), c


INC = """; ---------------------------------------------------------------------
;  gen_tex.inc -- GENERATED by engine2/tools/gentex.py.  Do not edit.
;
;  The addresses of RAM bank 5, the column renderer's table bank.  Bank 5
;  is paged in over &4000-&7FFF for the whole of raster_colframe and bank
;  4 is put back afterwards, so nothing else in the engine can see these.
; ---------------------------------------------------------------------
TEXCFG      equ #{ramcfg:02X}{ramcfg_c}
TEXWALL     equ #{wall:04X}          ; 16 pages of 256, transposed + x4
TEXDOOR     equ #{door:04X}
CTABT       equ #{ctab:04X}          ; 4 bytes per j: step.w, idx0.w
RTHRESH     equ #{rthr:04X}          ; 2 bytes per face width w

CTEX_BW     equ {texbw}              ; texture byte columns
CTEX_H      equ {texh}               ; texture rows
CIDX_N      equ {idxn}               ; ...replicated into a page this big
CJMAX       equ {jmax}               ; the largest half height, in SCANLINES
CHMAX       equ {chmax}              ; ...and in Q12.4, which is how CTABT
CIDXN       equ {cidxn}              ; is indexed: 4*(h>>2) == h & ~3
CNPAIR      equ {npair}              ; column PAIRS across the viewport
CFARB       equ #{farb:02X}              ; THE FAR PLANE's one byte -- the
                                    ; wall's SHADE pen doubled, which is
                                    ; what a stone wall reads as when it
                                    ; is too far for its texture to carry
CFARIDX     equ {faridx}              ; ...and an index into any wall page
                                    ; whose byte IS that.  rc_far walks
                                    ; with step 0, so the same byte comes
                                    ; out on every row and the ordinary
                                    ; fill draws a flat band for free.
TEXEND      equ #{end:04X}
"""


def write_inc(path, blob):
    c = rm.cfg()
    open(path, "w").write(INC.format(
        ramcfg=RAMCFG, ramcfg_c="        ; OUT (&7Fxx),this pages bank 5",
        wall=A_WALL, door=A_DOOR, ctab=A_CTAB, rthr=A_RTHR,
        texbw=colmodel.TEX_BW, texh=colmodel.TEX_H, idxn=colmodel.IDX_N,
        jmax=colmodel.JMAX, chmax=colmodel.HMAX_Q4,
        cidxn=colmodel.CIDX_N, npair=c.VP_BW // 2,
        farb=colmodel.far_byte(), faridx=colmodel.far_index(),
        end=BANK_BASE + len(blob)))


def main():
    blob, c = build()
    out = os.path.join(_E2, "build")
    os.makedirs(out, exist_ok=True)
    open(os.path.join(out, "TEX.BIN"), "wb").write(blob)
    write_inc(os.path.join(_E2, "src", "gen_tex.inc"), blob)
    print(f"bank 5: {len(blob)} of {BANK_SIZE} bytes, "
          f"{BANK_SIZE - len(blob)} free")
    print(f"  TEXWALL  #{A_WALL:04X}  {colmodel.TEX_BW} pages x "
          f"{colmodel.IDX_N}")
    print(f"  TEXDOOR  #{A_DOOR:04X}  {colmodel.TEX_BW} pages x "
          f"{colmodel.IDX_N}")
    print(f"  CTABT    #{A_CTAB:04X}  {colmodel.CIDX_N} x 4  (indexed in QUARTER scanlines)")
    print(f"  RTHRESH  #{A_RTHR:04X}  {c.VP_BW + 1} x 2")
    print(f"  -> engine2/build/TEX.BIN, engine2/src/gen_tex.inc")


if __name__ == "__main__":
    main()
